<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="QueryExecutorService" targetNamespace="http://ws.aridus.uern.br/" xmlns:ns1="http://model.aridus.uern.br/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://ws.aridus.uern.br/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/">
  <wsdl:import namespace="http://model.aridus.uern.br/" location="QueryExecutorIface.wsdl">
    </wsdl:import>
  <wsdl:binding name="QueryExecutorServiceSoapBinding" type="ns1:QueryExecutorIface">
    <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="execute2">
      <soap12:operation soapAction="" style="document"/>
      <wsdl:input name="execute2">
        <soap12:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="execute2Response">
        <soap12:body use="literal"/>
      </wsdl:output>
      <wsdl:fault name="IOException">
        <soap12:fault name="IOException" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="UnsupportedQueryResultFormatException">
        <soap12:fault name="UnsupportedQueryResultFormatException" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="QueryEvaluationException">
        <soap12:fault name="QueryEvaluationException" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="TupleQueryResultHandlerException">
        <soap12:fault name="TupleQueryResultHandlerException" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
    <wsdl:operation name="execute1">
      <soap12:operation soapAction="" style="document"/>
      <wsdl:input name="execute1">
        <soap12:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="execute1Response">
        <soap12:body use="literal"/>
      </wsdl:output>
      <wsdl:fault name="RepositoryException">
        <soap12:fault name="RepositoryException" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="IOException">
        <soap12:fault name="IOException" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="UnsupportedQueryResultFormatException">
        <soap12:fault name="UnsupportedQueryResultFormatException" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="QueryEvaluationException">
        <soap12:fault name="QueryEvaluationException" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="TupleQueryResultHandlerException">
        <soap12:fault name="TupleQueryResultHandlerException" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="QueryExecutorService">
    <wsdl:port name="QueryExecutorPort" binding="tns:QueryExecutorServiceSoapBinding">
      <soap12:address location="http://localhost:9090/QueryExecutorPort"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
