
package br.uern.aridus.model.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.7
 * Mon Jan 20 13:42:36 BRST 2014
 * Generated source version: 2.7.7
 */

@XmlRootElement(name = "alignImport", namespace = "http://model.aridus.uern.br/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "alignImport", namespace = "http://model.aridus.uern.br/")

public class AlignImport {

    @XmlElement(name = "urlid")
    private java.lang.String urlid;

    public java.lang.String getUrlid() {
        return this.urlid;
    }

    public void setUrlid(java.lang.String newUrlid)  {
        this.urlid = newUrlid;
    }

}

