
package br.uern.aridus.model.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.7
 * Mon Jan 20 14:00:53 BRST 2014
 * Generated source version: 2.7.7
 */

@XmlRootElement(name = "execute2", namespace = "http://model.aridus.uern.br/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "execute2", namespace = "http://model.aridus.uern.br/", propOrder = {"query", "endpoints"})

public class Execute2 {

    @XmlElement(name = "query")
    private java.lang.String query;
    @XmlElement(name = "endpoints")
    private String[] endpoints;

    public java.lang.String getQuery() {
        return this.query;
    }

    public void setQuery(java.lang.String newQuery)  {
        this.query = newQuery;
    }

    public String[] getEndpoints() {
        return this.endpoints;
    }

    public void setEndpoints(String[] newEndpoints)  {
        this.endpoints = newEndpoints;
    }

}

