
package br.uern.aridus.model.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.7
 * Mon Jan 20 14:00:53 BRST 2014
 * Generated source version: 2.7.7
 */

@XmlRootElement(name = "execute1", namespace = "http://model.aridus.uern.br/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "execute1", namespace = "http://model.aridus.uern.br/")

public class Execute1 {

    @XmlElement(name = "query")
    private java.lang.String query;

    public java.lang.String getQuery() {
        return this.query;
    }

    public void setQuery(java.lang.String newQuery)  {
        this.query = newQuery;
    }

}

