
package br.uern.aridus.model.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.7
 * Sat Jan 18 15:10:31 BRST 2014
 * Generated source version: 2.7.7
 */

@XmlRootElement(name = "getProp", namespace = "http://model.aridus.uern.br/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getProp", namespace = "http://model.aridus.uern.br/", propOrder = {"databset", "prop"})

public class GetProp {

    @XmlElement(name = "databset")
    private java.lang.String databset;
    @XmlElement(name = "prop")
    private java.lang.String prop;

    public java.lang.String getDatabset() {
        return this.databset;
    }

    public void setDatabset(java.lang.String newDatabset)  {
        this.databset = newDatabset;
    }

    public java.lang.String getProp() {
        return this.prop;
    }

    public void setProp(java.lang.String newProp)  {
        this.prop = newProp;
    }

}

