
package br.uern.aridus.model.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.7
 * Sat Jan 18 15:10:31 BRST 2014
 * Generated source version: 2.7.7
 */

@XmlRootElement(name = "listEndpointVocabs", namespace = "http://model.aridus.uern.br/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "listEndpointVocabs", namespace = "http://model.aridus.uern.br/")

public class ListEndpointVocabs {

    @XmlElement(name = "endpoint")
    private java.lang.String endpoint;

    public java.lang.String getEndpoint() {
        return this.endpoint;
    }

    public void setEndpoint(java.lang.String newEndpoint)  {
        this.endpoint = newEndpoint;
    }

}

