
package br.uern.aridus.model.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.7
 * Sat Jan 18 15:10:31 BRST 2014
 * Generated source version: 2.7.7
 */

@XmlRootElement(name = "listEndpointsByVocab", namespace = "http://model.aridus.uern.br/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "listEndpointsByVocab", namespace = "http://model.aridus.uern.br/")

public class ListEndpointsByVocab {

    @XmlElement(name = "vocab")
    private java.lang.String vocab;

    public java.lang.String getVocab() {
        return this.vocab;
    }

    public void setVocab(java.lang.String newVocab)  {
        this.vocab = newVocab;
    }

}

