
package br.uern.aridus.model.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.7
 * Sat Jan 18 15:10:31 BRST 2014
 * Generated source version: 2.7.7
 */

@XmlRootElement(name = "listDatasetsByVocabs", namespace = "http://model.aridus.uern.br/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "listDatasetsByVocabs", namespace = "http://model.aridus.uern.br/", propOrder = {"v0", "v1", "v2", "v3", "v4", "v5", "v6", "v7", "v8", "v9"})

public class ListDatasetsByVocabs {

    @XmlElement(name = "v0")
    private java.lang.String v0;
    @XmlElement(name = "v1")
    private java.lang.String v1;
    @XmlElement(name = "v2")
    private java.lang.String v2;
    @XmlElement(name = "v3")
    private java.lang.String v3;
    @XmlElement(name = "v4")
    private java.lang.String v4;
    @XmlElement(name = "v5")
    private java.lang.String v5;
    @XmlElement(name = "v6")
    private java.lang.String v6;
    @XmlElement(name = "v7")
    private java.lang.String v7;
    @XmlElement(name = "v8")
    private java.lang.String v8;
    @XmlElement(name = "v9")
    private java.lang.String v9;

    public java.lang.String getV0() {
        return this.v0;
    }

    public void setV0(java.lang.String newV0)  {
        this.v0 = newV0;
    }

    public java.lang.String getV1() {
        return this.v1;
    }

    public void setV1(java.lang.String newV1)  {
        this.v1 = newV1;
    }

    public java.lang.String getV2() {
        return this.v2;
    }

    public void setV2(java.lang.String newV2)  {
        this.v2 = newV2;
    }

    public java.lang.String getV3() {
        return this.v3;
    }

    public void setV3(java.lang.String newV3)  {
        this.v3 = newV3;
    }

    public java.lang.String getV4() {
        return this.v4;
    }

    public void setV4(java.lang.String newV4)  {
        this.v4 = newV4;
    }

    public java.lang.String getV5() {
        return this.v5;
    }

    public void setV5(java.lang.String newV5)  {
        this.v5 = newV5;
    }

    public java.lang.String getV6() {
        return this.v6;
    }

    public void setV6(java.lang.String newV6)  {
        this.v6 = newV6;
    }

    public java.lang.String getV7() {
        return this.v7;
    }

    public void setV7(java.lang.String newV7)  {
        this.v7 = newV7;
    }

    public java.lang.String getV8() {
        return this.v8;
    }

    public void setV8(java.lang.String newV8)  {
        this.v8 = newV8;
    }

    public java.lang.String getV9() {
        return this.v9;
    }

    public void setV9(java.lang.String newV9)  {
        this.v9 = newV9;
    }

}

