
package br.uern.aridus.model.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.7
 * Mon Jan 20 14:17:56 BRST 2014
 * Generated source version: 2.7.7
 */

@XmlRootElement(name = "RepositoryException", namespace = "http://repository.openrdf.org/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RepositoryException", namespace = "http://repository.openrdf.org/")

public class RepositoryExceptionBean {

    private java.lang.String message;

    public java.lang.String getMessage() {
        return this.message;
    }

    public void setMessage(java.lang.String newMessage)  {
        this.message = newMessage;
    }

}

